---

- import_playbook: bootstrap.yml
  tags:
    - bootstrap
- import_playbook: database.yml
- import_playbook: webserver.yml
- import_playbook: solr.yml
- import_playbook: tomcat.yml
- import_playbook: crayfish.yml
- import_playbook: karaf.yml
- import_playbook: post-install.yml
- import_playbook: setup_private_file_system.yml
- import_playbook: archival-integrity.yml 
- import_playbook: clamav.yml
- import_playbook: rdm-extra.yml

