---

- hosts: webserver
  become: yes

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-xdebug
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - geerlingguy.drupal
    - Islandora-Devops.drupal-openseadragon
    - webserver-app
    - Islandora-Devops.matomo
