---

drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "zaporylie/composer-drupal-optimizations:^1.0"
  - "drupal/console:~1.0"
  - "drupal/devel:*"
  - "drush/drush:^9.0"
  - "drupal/rdfui:^1.0-beta1"
  - "drupal/restui:^1.16"
  - "drupal/search_api_solr:^4.1"
  - "drupal/facets:^1.3"
  - "drupal/content_browser:^1.0@alpha"
  - "drupal/matomo:^1.7"
  - "drupal/pdf:1.x-dev"
  - "drupal/admin_toolbar:^2.0"
  - "drupal/rest_oai_pmh:^1.0"
  - "drupal/transliterate_filenames:^1.3"
  - "drupal/field_permissions:*"
  - "islandora-rdm/islandora_fits:dev-master" 
  - "islandora/carapace:dev-8.x-3.x"
  - "islandora/islandora:dev-8.x-1.x"
  - "islandora/controlled_access_terms:dev-8.x-1.x"
drupal_composer_project_package: "islandora/drupal-project:8.8.1"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal8
drupal_db_name: drupal8
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "127.0.0.1"
drupal_domain: "claw.dev"
drupal_site_name: "Islandora Research Data Management"
drupal_install_profile: standard
drupal_account_name: admin
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - simpletest
  - restui
  - devel
  - search_api_solr
  - search_api_solr_defaults
  - facets
  - content_browser
  - matomo
  - pdf
  - islandora_core_feature
  - admin_toolbar
  - transliterate_filenames
  - controlled_access_terms_defaults 
  - islandora_fits
#  - islandora_breadcrumbs
#  - islandora_iiif

drupal_trusted_hosts:
  - ^localhost$
  - "{{ hostvars[groups['webserver'][0]].ansible_host }}"
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_external_libraries_directory: "{{ drupal_core_path }}/libraries"
fedora_base_url: "http://{{ hostvars[groups['tomcat'][0]].ansible_host }}:8080/fcrepo/rest/"
drupal_jsonld_remove_format: true
drupal_gemini_pseudo_bundles:
  - islandora_object:node
  - image:media
  - file:media
  - audio:media
  - video:media
openseadragon_composer_item: "islandora/openseadragon:dev-8.x-1.x"
